FROM alpine:3.7

# RUN apk update && apk add \
#    pandoc
# TODO: Would have gotten overcomplicated as a starter project, but doable https://github.com/skyzyx/alpine-pandoc
# TODO: not sure that something like pandoc is needed in super minimal base image...
